
project_id = "jzvpgqtobzqbavsillqp"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.app"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
port = 54322

[studio]
enabled = true
port = 54323

[functions.clipogino-chat]
verify_jwt = true

[functions.generate-content]
verify_jwt = true

[functions.process-knowledge-file]
verify_jwt = true

[edge_runtime]
enabled = true
port = 54325
inspector_port = 5433
