// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzvpgqtobzqbavsillqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6dnBncXRvYnpxYmF2c2lsbHFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNTM0NjIsImV4cCI6MjA2MzgyOTQ2Mn0.pUUpZd-4FjpDgNquSHOX6nSk69LhX5zRAeVJvwqj3QE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);